version: "3.9"
volumes:
  data:
  app_data:
  redis_data:

services:
  postgres:
    image: postgres:alpine3.17
    # env_file:
    #   - .envs/.local.env
    environment:
      - POSTGRES_DB=fitdb
      - POSTGRES_USER=fitdbadmin
      - POSTGRES_PASSWORD=fitdbadminpassword12
    volumes:
      - "data:/var/lib/postgresql/data"
    restart: unless-stopped

  webapp:
    build: .
    command: >
      bash -c "alembic upgrade head &&
              uvicorn apps.main:app --port 8000 --host 0.0.0.0 --reload"
    env_file:
      - .envs/.local.env
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: .
        target: /src
    restart: always
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=dracula
