version: "3.9"
volumes:
  data:
  app_data:
  redis_data:

services:
  postgres:
    image: postgres:alpine3.17
    env_file:
      - .envs/.dev.env
    volumes:
      - "data:/var/lib/postgresql/data"
    restart: unless-stopped

  webapp:
    build: .
    command: >
      bash -c "alembic upgrade head &&
              uvicorn apps.main:app --port 8000 --host 0.0.0.0 --reload"
    env_file:
      - .envs/.dev.env
    depends_on:
      - postgres
    volumes:
      - app_data:/src
    restart: always
    ports:
      - "8003:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    environment:
      - ADMINER_DESIGN=dracula
